### ISSUE TITLE
Uncaught TypeError: 'set' on proxy: trap returned falsish for property 'items'

### ISSUE THREAD

**Issue by albertosantini** [WebReflection/striptease#2]
I get the error in the title.

https://plnkr.co/edit/r2wDN1ebqLjLkr1Oe9Gw?p=preview
```
"use strict";

class Foo {
    constructor() {
        this.state = Striptease(JSON.parse("{}"), console.log);

        this.state.items = [ // here Uncaught TypeError: 'set' on proxy: trap returned falsish for property 'items'
            { id: 1, text: "foo" },
            { id: 2, text: "bar" },
            { id: 3, text: "baz" }
        ];
    }

    add(newItem) {
        this.state.items.push(newItem);
    }
}

const foo = new Foo();

foo.add({ id: 4, text: "minions" });

console.log(foo.state);


```

I am sure I am missing something here.

**Comment by WebReflection** [comment]
can you try the following ?

```js
this.state = {
  items: [ ... ]
};
```

**Comment by WebReflection** [comment]
P.S. just in case, you don't need to `JSON.parse`, it can be any JSON serializable object 😉 
```js
this.state = Striptease({}, console.log);
```

**Comment by WebReflection** [comment]
Wow, this happens only inside the class !!!

The following is just fine, I'll try other browsers too to see if it's a V8 gotcha.
```js
const state = Striptease({}, console.log);
state.items = [
  { id: 1, text: "foo" },
  { id: 2, text: "bar" },
  { id: 3, text: "baz" }
];
```

**Comment by albertosantini** [comment]
Suggestion tested and it works fine. :)

```
class Foo {
    constructor() {
        const data = {
          items: [ 
            { id: 1, text: "foo" },
            { id: 2, text: "bar" },
            { id: 3, text: "baz" }
          ]
        };
        
        this.state = Striptease(data, console.log);
    }
...
```

It also makes sense to create the Striptease object at the end.

For me it is ok. You can close the issue, if finally it is not a reminder for other checks.

(hyperHTML, Striptease, wrist - nice stack!)

**Comment by WebReflection** [comment]
I honestly do not understand what the hell is going on.

I want this to work so it's not closed 'till it does!

Thanks

**Comment by WebReflection** [comment]
I think it was some V8 nonsense, but it's solved now. 🍻

**Comment by albertosantini** [comment]
I suppose the explanation is this one: 

- https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy/handler/set
`The set method should return a boolean value. Return true to indicate that assignment succeeded. If the set method returns false, and the assignment happened in strict-mode code, a TypeError will be thrown.`

**Comment by WebReflection** [comment]
now it returns always `true` as I don't see here any reason to throw otherwise.

**Comment by albertosantini** [comment]
Just a working example with hyperHTML.

And in this case Striptease object is create at the beginning (previously I said it was better at the end, but, I suppose, it depends on the use case) to avoid also the initial manual update.

Nice the reference between `root`, the first parameter of Striptease callback, and `state` object, used in the template with the name `$ctrl`.

`this.update.bind(this)` is a bit ugly: it is for render function. 
Anyway this kind of remarks are more in hyperHTML realm. :) Ignore it.

```
"use strict";

class Foo {
    constructor() {
        this.render = hyperHTML.bind(document.body);

        this.state = Striptease({}, this.update.bind(this));
        this.state.items = [
            { id: 1, text: "foo" },
            { id: 2, text: "bar" },
            { id: 3, text: "baz" }
        ];
    }

    update($ctrl) {
        this.render`
            <ul>${$ctrl.items.map(item => hyperHTML.wire()`
                <li> ${item.id} / ${item.text} </li>
            `)}</ul>
        `;
    }
}

const foo = new Foo();

setTimeout(() => {
    foo.state.items.push({ id: 4, text: "minions" });
}, 3000);
```

**Comment by WebReflection** [comment]
```js
item => hyperHTML.wire(item)
```
if you use an empty wire each time you'll create and parse a new node ... when you can avoid that, like in this case where a wire is mapped to an object, pass the object along 😉

**Comment by WebReflection** [comment]
BTW, that is an **excellent** example, and one of the reason `Striptease` was born in the first place 🎉
